version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: registrationdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    ports:
      - "8080:80"

volumes:
  pgdata: